#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DEADLY_REPO == "DEADLY-OP-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9kZWFkbHktb3AtdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $DEADLY_REPO == "DEADLY-OP-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9kZWFkbHktb3AtdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $DEADLY_REPO =~ $regex ]]
    then
        if [[ $DEADLY_REPO_BRANCH ]]
        then
            echo "${DEADLY_REPO}/archive/${DEADLY_REPO_BRANCH}.zip"
        else
            echo "${DEADLY_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9kZWFkbHktb3AtdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="DeadlyBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting  DeadlyBot  "
    echo "

                                  Deadly Bot
                          
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
