#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAFIA_REPO == "elitebot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9lbGl0ZXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $MAFIA_REPO == "ELITEBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9lbGl0ZXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $MAFIA_REPO =~ $regex ]]
    then
        if [[ $MAFIA_REPO_BRANCH ]]
        then
            echo "${MAFIA_REPO}/archive/${MAFIA_REPO_BRANCH}.zip"
        else
            echo "${MAFIA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9lbGl0ZXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting elites bot   "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          
                         Elites bot       elites bot
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
